// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fghugaorggnutvvusoip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnaHVnYW9yZ2dudXR2dnVzb2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTY1MTUsImV4cCI6MjA2MjM3MjUxNX0.P1Q30dxc_mZy6uGM68574w56eJRsY7wlthTYbUTrjto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);